name: "Build & Push Docker image"

on:
  release:
    types: [ published ]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@master

      - name: "Log in to the Container registry"
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push Docker image"
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}
          tags: ghcr.io/${{ github.repository }}:latest
